dist: trusty

sudo: required

notifications:
  email: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
 global:
  - SWIG=swig3.0
  - PY_FDN="python$(python --version | cut -f2 -d' ' | cut -f1 -d.)"
 matrix:
  - CC=gcc-5 PYSAM_VERSION='pysam==0.9.0'
  - CC=gcc PYSAM_VERSION='pysam==0.9.0'
  - CC=gcc-5 PYSAM_VERSION='pysam'
  - CC=gcc PYSAM_VERSION='pysam'

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-5
     - g++-5

before_install:
  - sudo add-apt-repository ppa:nschloe/swig-backports -y
  - sudo apt-get -qq update
  - sudo apt-get install -y swig3.0

install:
  # setuptools < 18.0 has issues with Cython as a dependency
  - pip install Cython
  - sed -i "s/pysam>=0.9.0/$PYSAM_VERSION/" setup.py
  # old setuptools also has a bug for extras, but it still compiles
  - pip install '.[htseq-qa]'
 
script:
  - python $PY_FDN/test/test.py
